### ISSUE TITLE
How often does the sidecar send metrics to stackdriver?

### ISSUE THREAD

**Issue by anderson4u2** [Stackdriver/stackdriver-prometheus-sidecar#103]
Unless I've missed it in the README and the google docs page, don't think this is documented.

Just wondering how often does this sidecar send metrics to the stackdriver endpoint? 

Thanks!

Anderson

**Comment by fabxc** [comment]
When the sidecar is operating normally, it will detect new datapoints as they are written by Prometheus and sends them to Stackdriver almost immediately.

**Comment by anderson4u2** [comment]
thanks for the quick reply, feel free to close this issue :+1:

**Comment by jkohen** [comment]
Thanks both!
