### ISSUE TITLE
Prometheus metrics are shown on Stackdriver graphs with a delay which increases over time

### ISSUE THREAD

**Issue by koustubhg** [Stackdriver/stackdriver-prometheus-sidecar#137]
Prometheus version: v2.11.1    
Prometheus scrapeInterval: 60s
Sidecar image: 0.4.3

I am using the following script to inject to sidecar to Prometheus

```
#!/bin/sh

# ./patch.sh deployment prometheus

export GCP_PROJECT="myproject"
export DATA_DIR="/data"
export GCP_REGION="australia-southeast1-a"
export KUBE_CLUSTER="mycluster"
export DATA_VOLUME="data-volume"
export KUBE_NAMESPACE="mynamespace"
export SIDECAR_IMAGE_TAG="0.4.3"
export API_ADDRESS="http://127.0.0.1:9090"

set -e
set -u

usage() {
  echo -e "Usage: $0 <deployment|statefulset> <name>\n"
}

if [  $# -le 1 ]; then
  usage
  exit 1
fi

# Override to use a different Docker image name for the sidecar.
export SIDECAR_IMAGE_NAME=${SIDECAR_IMAGE_NAME:-'gcr.io/stackdriver-prometheus/stackdriver-prometheus-sidecar'}

kubectl -n "${KUBE_NAMESPACE}" patch "$1" "$2" --type strategic --patch "
spec:
  template:
    spec:
      containers:
      - name: stackdriver-prometheus-sidecar
        image: ${SIDECAR_IMAGE_NAME}:${SIDECAR_IMAGE_TAG}
        imagePullPolicy: Always
        args:
        - \"--stackdriver.project-id=${GCP_PROJECT}\"
        - \"--prometheus.wal-directory=${DATA_DIR}/wal\"
        - \"--prometheus.api-address=$API_ADDRESS\"
        - \"--stackdriver.kubernetes.location=${GCP_REGION}\"
        - \"--stackdriver.kubernetes.cluster-name=${KUBE_CLUSTER}\"
        - \"--stackdriver.generic.location=${GCP_REGION}\"
        - \"--stackdriver.generic.namespace=${KUBE_NAMESPACE}\"
        - \"--log.level=debug\"
        ports:
        - name: sidecar
          containerPort: 9091
        volumeMounts:
        - name: ${DATA_VOLUME}
          mountPath: ${DATA_DIR}  
"

```
I have a shared volume between prometheus and sidecar and I can also see the metrics on stackdriver (image attached below)

![image](https://user-images.githubusercontent.com/44349550/62188254-6ea96f00-b389-11e9-9fc9-e8383f797c9e.png)

The metrics start to show as soon as the sidecar is started, however as time passes it gets much slower (image attached)

I tried to change the `prometheus scrape interval` (increasing and reducing value), however it didn't solve the problem.
I can see the metrics in corresponding grafana, so prometheus is definitely working as expected.

With debug level logs enabled, I couldn't see any relevant error in the sidecar logs
```
level=debug ts=2019-07-31T06:27:35.185540233Z caller=client.go:98 component=storage msg="is auth enabled" auth=true url=https://monitoring.googleapis.com:443/
level=debug ts=2019-07-31T06:27:35.186037989Z caller=client.go:98 component=storage msg="is auth enabled" auth=true url=https://monitoring.googleapis.com:443/
level=debug ts=2019-07-31T06:27:35.186576582Z caller=client.go:98 component=storage msg="is auth enabled" auth=true url=https://monitoring.googleapis.com:443/
level=debug ts=2019-07-31T06:27:35.186680101Z caller=client.go:98 component=storage msg="is auth enabled" auth=true url=https://monitoring.googleapis.com:443/
level=debug ts=2019-07-31T06:27:40.058755991Z caller=queue_manager.go:318 component=queue_manager msg=QueueManager.calculateDesiredShards samplesIn=148.0967934133026 samplesOut=125.71924386807879 samplesOutDuration=1.139403333028691e+09 timePerSample=9.063078157106189e+06 sizeRate=18171.723407587924 offsetRate=253.1304316466789 desiredShards=144.53212821608827
level=debug ts=2019-07-31T06:27:40.058873253Z caller=queue_manager.go:329 component=queue_manager msg=QueueManager.updateShardsLoop lowerBound=16.099999999999998 desiredShards=144.53212821608827 upperBound=25.3
level=debug ts=2019-07-31T06:27:40.058951793Z caller=queue_manager.go:349 component=queue_manager msg="Remote storage resharding" from=23 to=145
level=debug ts=2019-07-31T06:27:55.058719537Z caller=queue_manager.go:318 component=queue_manager msg=QueueManager.calculateDesiredShards samplesIn=118.47743473064209 samplesOut=119.2020617611297 samplesOutDuration=1.1689497355696194e+09 timePerSample=9.806455679534221e+06 sizeRate=22098.072059403672 offsetRate=202.5043453173431 desiredShards=190.17744566184993
level=debug ts=2019-07-31T06:27:55.058836748Z caller=queue_manager.go:329 component=queue_manager msg=QueueManager.updateShardsLoop lowerBound=101.5 desiredShards=190.17744566184993 upperBound=159.5
level=debug ts=2019-07-31T06:27:55.058859951Z caller=queue_manager.go:352 component=queue_manager msg="Currently resharding, skipping" to=191
```

Did I miss something in the configuration?

**Comment by jkohen** [comment]
@koustubhg thanks for the report. Your configuration looks fine. I need more information about your setup. Can you follow the triage instructions[1]?

We also haven't tested the integration against this version of Prometheus[2]. Are you able to test with Prometheus 2.6 and let us know whether you still see the problem?

@StevenYCChou you've looked at similar issues. Any thoughts?

[1] https://github.com/Stackdriver/stackdriver-prometheus-sidecar/blob/master/docs/operations.md#verify-that-the-sidecar-operates-correctly
[2] Full compatibility matrix at https://github.com/Stackdriver/stackdriver-prometheus-sidecar#compatibility

**Comment by koustubhg** [comment]
@jkohen 
**triage instructions**


> Does the sidecar process Prometheus's data?
rate(prometheus_sidecar_samples_processed[5m])
213.95

> Are samples being sent to Stackdriver?
rate(prometheus_sidecar_samples_produced[5m])
57.621313510945924

rate(prometheus_remote_storage_succeeded_samples_total[5m])
108.82083333333334

> Can the sidecar keep up with Prometheus?

rate(prometheus_sidecar_samples_processed[5m]) ->  205.05833333333334
rate(prometheus_tsdb_head_samples_appended_total[5m]) -> 1579.8166666666666

The sidecar's processes samples above are notably lower. Here are the logs

> evel=debug ts=2019-08-07T03:40:30.6912521Z caller=client.go:169 component=storage msg="Partial failure calling CreateTimeSeries" err="rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: external.googleapis.com/prometheus/scrape_samples_post_metric_relabeling, Timestamps: {Youngest Existing: '2019/08/06-05:00:58.582', New: '2019/08/06-05:01:02.613'}}: timeSeries[0-2]"
> level=warn ts=2019-08-07T03:40:30.691379431Z caller=queue_manager.go:546 component=queue_manager msg="Unrecoverable error sending samples to remote storage" err="rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: external.googleapis.com/prometheus/scrape_samples_post_metric_relabeling, Timestamps: {Youngest Existing: '2019/08/06-05:00:58.582', New: '2019/08/06-05:01:02.613'}}: timeSeries[0-2]"
> level=debug ts=2019-08-07T03:40:32.651147811Z caller=client.go:169 component=storage msg="Partial failure calling CreateTimeSeries" err="rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: external.googleapis.com/prometheus/up, Timestamps: {Youngest Existing: '2019/08/06-05:00:58.582', New: '2019/08/06-05:01:02.613'}}: timeSeries[124-129]"
> level=warn ts=2019-08-07T03:40:32.651263051Z caller=queue_manager.go:546 component=queue_manager msg="Unrecoverable error sending samples to remote storage" err="rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: external.googleapis.com/prometheus/up, Timestamps: {Youngest Existing: '2019/08/06-05:00:58.582', New: '2019/08/06-05:01:02.613'}}: timeSeries[124-129]"
> level=debug ts=2019-08-07T03:40:32.65467099Z caller=client.go:169 component=storage msg="Partial failure calling CreateTimeSeries" err="rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: external.googleapis.com/prometheus/scrape_samples_scraped, Timestamps: {Youngest Existing: '2019/08/06-05:00:58.582', New: '2019/08/06-05:01:02.613'}}: timeSeries[82-95]"
> level=warn ts=2019-08-07T03:40:32.654781961Z caller=queue_manager.go:546 component=queue_manager msg="Unrecoverable error sending samples to remote storage" err="rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: external.googleapis.com/prometheus/scrape_samples_scraped, Timestamps: {Youngest Existing: '2019/08/06-05:00:58.582', New: '2019/08/06-05:01:02.613'}}: timeSeries[82-95]"
> level=debug ts=2019-08-07T03:40:32.661194206Z caller=client.go:169 component=storage msg="Partial failure calling CreateTimeSeries" err="rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: external.googleapis.com/prometheus/scrape_duration_seconds, Timestamps: {Youngest Existing: '2019/08/06-05:00:58.582', New: '2019/08/06-05:01:02.613'}}: timeSeries[110-114]"

prometheus_remote_storage_queue_length{queue="https://monitoring.googleapis.com:443/"} -> 601
prometheus_remote_storage_queue_capacity{queue="https://monitoring.googleapis.com:443/"} -> 600

I will try and filter the data that needs to be passed to stackdriver

**Prometheus 2.6**

I tried testing with this version, it still gives me the same problem.

**Comment by jkohen** [comment]
Yes, investigating why the sidecar can't keep up is a good place to start. Does it get enough access to CPU?  usage starved?

Can you share your Prometheus configuration? The errors in the logs don't explain the problem, but they could hint at something that's caused a higher volume of points than expected.

**Comment by koustubhg** [comment]
@jkohen 
I tried filtering the data being passed to Stackdriver using namespace following this https://github.com/Stackdriver/stackdriver-prometheus-sidecar/blob/master/README.md#filters

**And it works as expected.** 
We have several services reporting data to prometheus (including istio), while I need only specific data. So, filtering data does solve my problem.
Thanks for the help. You can close this issue if you want.

**Comment by jkohen** [comment]
@koustubhg thanks for the update; I'm glad you got it to work. If you run into this issue again, please ensure the sidecar has sufficient CPU allocated, as I suspect that's the cause of the lag you were seeing.
