### ISSUE TITLE
add prometheus operator docs

### ISSUE THREAD

**Issue by philips** [Stackdriver/stackdriver-prometheus-sidecar#141]
This sidecar seems to work with the prometheus operator (once I figure out the service account #136).

See https://github.com/merklecounty/rget/blob/master/production/prometheus.yaml#L38-L65

**Comment by jkohen** [comment]
Thanks for the report, I'm glad you made it work. We also provide instructions at https://github.com/Stackdriver/stackdriver-prometheus-sidecar/tree/master/kube

I'll see what we can do to make this more visible in our documentation.

**Comment by philips** [comment]
No, the problem is it isn't working. I still can't get it to work.

**Comment by jkohen** [comment]
I've responded to #142 separately. We'll use this issue to track your feedback to document that Prometheus Operator works.

**Comment by philips** [comment]
Sounds good, thanks for the reply

**Comment by parkjam4** [comment]
The following doc was updated with a link to setting permissions on your service account:
https://cloud.google.com/monitoring/kubernetes-engine/prometheus
