### ISSUE TITLE
Support newer versions of Prometheus

### ISSUE THREAD

**Issue by mans0954** [Stackdriver/stackdriver-prometheus-sidecar#151]
According to the README, stackdriver-prometheus-sidecar supports Prometheus 2.4.3 - Prometheus 2.6.x. There have been several releases of Prometheus since 2.6.x, most recently 2.12.0. Please could a newer versions be supported?

Thanks.

**Comment by StevenYCChou** [comment]
Hi @mans0954, Thanks for the question!

The latest stackdriver-prometheus-sidecar might support 2.6+, as I briefly scanned through the release notes of Prometheus, I didn't see any breaking change. We also updated our dependency to use what's provided in 2.11.1, which is close to latest Prometheus.

However we haven't been able to test the stackdriver-prometheus-sidecar against newer version. Before we update the compatibility matrix, what we run are unit test (which is covered when you run `make test`) and [e2e-test](https://github.com/Stackdriver/stackdriver-prometheus-e2e). If you happen to test them, feel free to create a PR and we will update the README. thanks!

**Comment by StevenYCChou** [comment]
As I answered you question, and I added more descriptions to clarify versions not shown in the compatibility section of README, I think it should resolve your concern, so I will close this issue now.

Feel free to reopen this issue if you still have question on this topic. Thanks!
