### ISSUE TITLE
Count values shoot off to infinity

### ISSUE THREAD

**Issue by mans0954** [Stackdriver/stackdriver-prometheus-sidecar#152]
Some of our metrics from our Kubernetes app sent to Stackdriver via stackdriver-prometheus-sidecar result in Stackdriver graphs which shoot off to infinity. Our alerts are triggered when this happens. Plots for the same time series look normal in Prometheus. I was wondering if anyone else is experiencing this, or could suggest what the cause was?

![Selection_065](https://user-images.githubusercontent.com/4855578/63363947-7e0a4f80-c36c-11e9-8142-6bcb33306f6e.png)
![Selection_067](https://user-images.githubusercontent.com/4855578/63363952-82cf0380-c36c-11e9-9cee-6f8eda35383f.png)
![Selection_069](https://user-images.githubusercontent.com/4855578/63364010-9da17800-c36c-11e9-80f9-bdd136a94a65.png)

Thanks for any assistance you can give.

**Comment by mans0954** [comment]
I can provide more detailed information about this issue. It seems to be triggered by pod deletion (occasionally we have seen the metric start at infinity when creating a pod too). 

We have a summary Prometheus metric `timer_http_request`. I deleted the `tpdsworker-stag-7784696774-wvknh` pod around 12.06 BST (=11.06 UTC). As you would expect, in Prometheus the graph simply stops once the pod is deleted:

![tpdsworker-stag-7784696774-wvknh_prometheus_no_status](https://user-images.githubusercontent.com/4855578/63524392-dc156f00-c4f3-11e9-98b2-85ed246b27f1.png)

However, in Stackdriver, the plot shoots off to infinity once the pod is deleted:

![tpdsworker-stag-7784696774-wvknh_stackdriver_no_status](https://user-images.githubusercontent.com/4855578/63524455-f4858980-c4f3-11e9-978e-4e01854e3972.png)

Is there a way to prevent this behaviour?

Thanks.

**Comment by mans0954** [comment]
I've now got some evidence that points to this being an issue with stackdriver-prometheus-sidecar rather than Prometheus or Stackdriver. I'm using the `--stackdriver.store-in-files-directory` option to write the data stackd'veriver-prometheus-sidecar would send to Stackdriver to file instead. I've then written a simple script to find the timeseries for the pod I'm deleting and output the values in human readable form:
```
go run sdpb.go 
2019-08-24 08:45:37.886 +0100 BST - 2019-08-24 08:46:37.886 +0100 BST 2
2019-08-24 08:45:37.886 +0100 BST - 2019-08-24 08:46:37.886 +0100 BST 2
2019-08-24 08:45:37.886 +0100 BST - 2019-08-24 08:46:37.886 +0100 BST 1
2019-08-24 08:45:37.886 +0100 BST - 2019-08-24 08:46:37.886 +0100 BST 0
2019-08-24 08:45:37.886 +0100 BST - 2019-08-24 08:46:37.886 +0100 BST 0
2019-08-24 08:45:37.886 +0100 BST - 2019-08-24 08:47:37.887 +0100 BST 4
2019-08-24 08:45:37.886 +0100 BST - 2019-08-24 08:47:37.887 +0100 BST 4
2019-08-24 08:45:37.886 +0100 BST - 2019-08-24 08:47:37.887 +0100 BST 2
2019-08-24 08:45:37.886 +0100 BST - 2019-08-24 08:47:37.887 +0100 BST 0
2019-08-24 08:45:37.886 +0100 BST - 2019-08-24 08:47:37.887 +0100 BST 0
2019-08-24 08:45:37.886 +0100 BST - 2019-08-24 08:48:37.886 +0100 BST 6
2019-08-24 08:45:37.886 +0100 BST - 2019-08-24 08:48:37.886 +0100 BST 6
2019-08-24 08:45:37.886 +0100 BST - 2019-08-24 08:48:37.886 +0100 BST 3
2019-08-24 08:45:37.886 +0100 BST - 2019-08-24 08:48:37.886 +0100 BST 0
2019-08-24 08:45:37.886 +0100 BST - 2019-08-24 08:48:37.886 +0100 BST 0
2019-08-24 08:45:37.886 +0100 BST - 2019-08-24 08:49:37.886 +0100 BST -9223372036854775808
2019-08-24 08:45:37.886 +0100 BST - 2019-08-24 08:49:37.886 +0100 BST -9223372036854775808
2019-08-24 08:45:37.886 +0100 BST - 2019-08-24 08:49:37.886 +0100 BST -9223372036854775808
2019-08-24 08:45:37.886 +0100 BST - 2019-08-24 08:49:37.886 +0100 BST -9223372036854775808
2019-08-24 08:45:37.886 +0100 BST - 2019-08-24 08:49:37.886 +0100 BST -9223372036854775808
```
The Graph plot in Prometheus is completely flat:
![tpdsworker-stag-7784696774-x6cqg_prometheus](https://user-images.githubusercontent.com/4855578/63634521-9a014000-c64f-11e9-96e2-8b44760010d9.png)

So it looks to me like the huge negative value `-9223372036854775808` is getting erroneously added to the metric by the sidecar as it is not in Prometheus as far as I can see.

For reference here is the script:
```
package main

import (
  "fmt"
  monitoring_pb "google.golang.org/genproto/googleapis/monitoring/v3"
  "github.com/golang/protobuf/proto"
  "io/ioutil"
  "log"
  "time"
)

func main() {
  app := "tpdsworker"
  host := "tpdsworker-stag-7784696774-x6cqg"
  in, err := ioutil.ReadFile("sidecar.bin")
  if err != nil {
      log.Fatalln("Error reading file:", err)
  }
  time_series_req := &monitoring_pb.CreateTimeSeriesRequest{}
  if err := proto.Unmarshal(in, time_series_req); err != nil {
    log.Fatalln("Failed to parse time_series_req:", err)
  }
  for _,time_series := range time_series_req.TimeSeries {
    if time_series.Metric.Type != "external.googleapis.com/prometheus/timer_http_request_count" { continue }
    if time_series.Metric.Labels["exported_app"] != app { continue }
    if time_series.Metric.Labels["host"] != host { continue }
    if time_series.Metric.Labels["path"] == "status" { continue }
    for _,point := range time_series.Points {
      start := time.Unix(point.Interval.GetStartTime().GetSeconds(),int64(point.Interval.GetStartTime().GetNanos()))
      end := time.Unix(point.Interval.GetEndTime().GetSeconds(),int64(point.Interval.GetEndTime().GetNanos()))
      //fmt.Println(point.Interval.GetEndTime().GetNanos())
      switch x := point.Value.Value.(type) {
        case *monitoring_pb.TypedValue_BoolValue:
          fmt.Println("Bool")
          _ = x
        case *monitoring_pb.TypedValue_Int64Value:
          fmt.Printf("%v - %v %v\n",start,end,point.Value.GetInt64Value())
        case *monitoring_pb.TypedValue_DoubleValue:
          fmt.Println("Double")
        case *monitoring_pb.TypedValue_StringValue:
          fmt.Println("String")
        case *monitoring_pb.TypedValue_DistributionValue:
          fmt.Println("Distribution")
      }
    }
  }
}

**Comment by mans0954** [comment]
@jkschulz - thanks. The sidecar is being run with the command:
```
/bin/stackdriver-prometheus-sidecar --stackdriver.project-id=ol-stag --prometheus.wal-directory=/data/wal --include={__name__=~".+",job="kubernetes-pods"}
```
Prometheus config: [prometheus.yml](https://github.com/Stackdriver/stackdriver-prometheus-sidecar/files/3547210/prometheus.yml.txt)

**Comment by mans0954** [comment]
@jkschulz - To help pin down what is going on, I have created a minimal app which generates a summary metric `timer_http_request`. You can find the source code here: https://github.com/mans0954/testsummary and the docker image  is on docker hub as `mans0954/testsummarymetric`. There is a simple script https://github.com/mans0954/testsummary/blob/master/traffic.sh which will deploy the image and then generate some traffic for the metric to measure. I let it run for 30 min or so, and it produced a reasonable graph in Stackdriver:

![test-summary-stackdriver-pre-delete](https://user-images.githubusercontent.com/4855578/63847904-aa365980-c986-11e9-9dfb-f1b570a18865.png)

I then pressed Ctrl-C to stop the traffic and delete the pod. The Stackdriver graph exhibited the undesirable behaviour:

![test-summary-stackdriver-post-delete](https://user-images.githubusercontent.com/4855578/63847951-c20ddd80-c986-11e9-8421-8a9da38dac85.png)

The graph in Prometheus did not exhibit this behaviour:

![test-summary-promethus-post-delete](https://user-images.githubusercontent.com/4855578/63847979-d0f49000-c986-11e9-8f37-479d70bd3a95.png)

Hopefully you will be able to use the traffic.sh script to reproduce the issue in your environment?

**Comment by mans0954** [comment]
As a sort-of work around, I've produced a modified version of stackdriver-prometheus-sidecar, which drops summary _count values approaching the limits of a 64 bit int:

https://github.com/overleaf/stackdriver-prometheus-sidecar/blob/csh-issue-455-count-values/retrieval/transform.go#L99-L106

This doesn't completely eliminate the spiking, but it keeps it to within an order of magnitude of the legitimate data. I don't consider it to be a fix for the underlying issue, whatever that may be.

**Comment by mans0954** [comment]
We've seen this issue with both version 0.4.3 and version 0.5.0.

**Comment by mans0954** [comment]
@jkschulz have you been able to reproduce the issue?

**Comment by bmoyles0117** [comment]
@qingling128 would you be able to take this over?

**Comment by qingling128** [comment]
Yeah, sorry for the delay. This has been a heavy oncall week with multiple release blocker issues. I'll take a look once the release is unblocked.

**Comment by mans0954** [comment]
@jkschulz Are you able to reproduce the issue in your environment?

**Comment by jkschulz** [comment]
@mans0954 Yes, I was able to reproduce the issue using your script -- thanks for that! I'm working to isolate the issue in the sidecar and will let you know what I find within the next day.

**Comment by mans0954** [comment]
@jkschulz - Thanks. At least it's not just me! Have you been able to identify the source of the problem?

**Comment by jkschulz** [comment]
@mans0954 Yes, it looks like Prometheus returns NaN if there aren't any samples in a certain time period (this is expected) for a quantile, so this is what we see once the pod goes down. This gets legally stored as a float. 

When the diff for the new set of samples is [calculated](https://github.com/Stackdriver/stackdriver-prometheus-sidecar/blob/master/retrieval/transform.go#L96), [`NaN-x = NaN`](https://github.com/Stackdriver/stackdriver-prometheus-sidecar/blob/master/retrieval/series_cache.go#L311), and then the final [cast to an int64](https://github.com/Stackdriver/stackdriver-prometheus-sidecar/blob/master/retrieval/transform.go#L101) results in the -9223372036854775808 value you see ([cast example](https://play.golang.org/p/ZEzSZozeUci)).

I'm working on a fix now.

**Comment by StevenYCChou** [comment]
> @mans0954 Yes, it looks like Prometheus returns NaN if there aren't any samples in a certain time period (this is expected) for a quantile, so this is what we see once the pod goes down. This gets legally stored as a float.

I'd like to follow up on what @jkschulz said and for your reference, a member of Prometheus also answered [why NaN is reported](https://github.com/prometheus/prometheus/issues/860#issuecomment-115614868) if you are curious to know. The same thread also suggests using a Histogram rather a Summary if you want more control. Also if you do not want a point get skipped once #186 is closed, you may consider using Histogram as well.

**Comment by jkschulz** [comment]
[0.6.2](https://github.com/Stackdriver/stackdriver-prometheus-sidecar/releases/tag/0.6.2) has been released, which includes this fix.
