### ISSUE TITLE
Project fails to build due to https://git.apache.org/ being down

### ISSUE THREAD

**Issue by mans0954** [Stackdriver/stackdriver-prometheus-sidecar#162]
```
make
>> formatting code
GO111MODULE=on go fmt ./...
go: finding git.apache.org/thrift.git v0.0.0-20180902110319-2566ecd5d999
go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f https://git.apache.org/thrift.git refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/mans0954/go/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
	fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Connection timed out
go: error loading module requirements
Makefile:81: recipe for target 'format' failed
make: *** [format] Error 1
```
I appreciate that the unavailability of git.apache.org is outside of this projects control, but Apache seem to be moving towards using GitHub for VCS [1], and the installation instructions for thrift now refer to the GitHub url [2], so it may be advisable to add a replace statement to `go.mod`.

[1] https://blogs.apache.org/foundation/entry/the-apache-software-foundation-expands
[2] https://github.com/apache/thrift/tree/master/lib/go#using-thrift-with-go

**Comment by ankushchadha** [comment]
To make builds more deterministic, I would recommend setting GOPROXY to https://gocenter.io. GoCenter (central Go modules repository) has both old and new module versions sine we guarantee immutability and availability. 

Example: https://search.gocenter.io/git.apache.org~2Fthrift.git/info or https://search.gocenter.io/github.com~2Fapache~2Fthrift/info (new module)

**Comment by qingling128** [comment]
Seems fixed by https://github.com/Stackdriver/stackdriver-prometheus-sidecar/pull/170.
