### ISSUE TITLE
Node-exporter uses deprecated apiVersion

### ISSUE THREAD

**Issue by JoarLeth** [Stackdriver/stackdriver-prometheus-sidecar#230]
Hey 👋
I deployed this project in a cluster a few months back and now we're planning to upgrade to k8s version 1.6. I noticed that the node-exporter (https://github.com/Stackdriver/stackdriver-prometheus-sidecar/blob/master/kube/full/node-exporter.yaml) uses `apiVersion: apps/v1beta2` for the `DaemonSet` which is deprecated and removed from Kubernetes as of version 1.16 (https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/). Are there any plans to support version 1.16 of the k8s API? I wasn't able to find any information about supported k8s API versions, sorry if I've missed something.

**Comment by igorpeshansky** [comment]
Thanks for the report. The fix is being reviewed.
