### ISSUE TITLE
Document how to use --filter to send specific metrics

### ISSUE THREAD

**Issue by jerub** [Stackdriver/stackdriver-prometheus-sidecar#61]
https://github.com/Stackdriver/stackdriver-prometheus-sidecar/issues/45 implements the filtering mechanism, by passing `--filter=...` repeatedly we can elect to send only specific metrics to stackdriver.

This doesn't seem to be documented anywhere (except in the help text). It would be nice to have a few examples in place so that someone can easily set this up.

**Comment by jkohen** [comment]
@fabxc you had some thoughts about documenting this (or not). Can you take a look?

**Comment by fabxc** [comment]
@jerub do the new docs in the README resolve this issue?

**Comment by fabxc** [comment]
Considering this fixed.
