### ISSUE TITLE
target refresh failed: unexpected response status: 404 Not Found

### ISSUE THREAD

**Issue by ToxicWar** [Stackdriver/stackdriver-prometheus-sidecar#71]
Hi,

I try to use `stackdriver-prometheus-sidecar` with my `prometheus-server` who installed used `stable/prometheus` helm chart.

I configure my `stackdriver-prometheus-sidecar` with `--prometheus.api-address=http://127.0.0.1:9090/prometheus/`, because in Prometheus deployment I use `prefixURL`.

Then when my pod with `stackdriver-prometheus-sidecar` I see errors like this and zero metrics in Stackdriver.

```
level=error ts=2018-12-31T07:41:16.764201212Z caller=cache.go:76 msg="refresh failed" err="unexpected response status: 404 Not Found"
level=warn ts=2018-12-31T07:42:13.044253069Z caller=manager.go:243 component="Prometheus reader" msg="Failed to build sample" err="get series information: retrieving target failed: target refresh failed: unexpected response status: 404 Not Found"
``` 

As I understand it's some problem with `targetsURL`, because service try get data from `/api/v1/targets/metadata` without using `prefixURL` specified in `prometheus.api-address`

```
targetsURL, err := cfg.prometheusURL.Parse(targets.DefaultAPIEndpoint)
```

**Comment by jkohen** [comment]
Thanks for the report. Release 0.3.1 includes the fix.
