### ISSUE TITLE
Parsing order

### ISSUE THREAD

**Issue by polycaster** [Stackdriver/stackdriver-prometheus-sidecar#78]
Hi all,

I've been implementing the sidecar across multiple environments.
On my tests I've come across an issue that i'd like to bring up.

`level=debug ts=2019-01-18T18:20:44.295817108Z caller=client.go:162 component=storage msg="Partial failure calling CreateTimeSeries" err="rpc error: code = InvalidArgument desc = Field timeSeries[0].points[0].interval.end had an invalid value of \"2019-01-14T23:14:16.842-08:00\": Data points cannot be written more than 24h in the past." `

I understand that there is a time limit of 24 hours, because you wouldn't want to store historical metric data, however, after trying to parse ~150 entries that are older than the 24 limit the container seems to stop attempting to parse anything younger than that.
You'll find attached the logs that the sidecar outputted. 
[logs.txt](https://github.com/Stackdriver/stackdriver-prometheus-sidecar/files/2774116/logs.txt)

I guess my question here is, why doesn't the parsing start from the most recent entry, rather than looking at historical data first?
If there is a hard limit of 24 hours, it would make sense to work your way towards that limit and once you reach it, cut off, rather than trying to parse entries that have the potential of being rejected.

Could you clarify this design decision for me and advise me what to do regarding the problem I currently have?

Thank you very much for your time.
Miguel

**Comment by polycaster** [comment]
An update on the above, the reason why the container stopped working was because it ran out of memory.

Upping the limit to 5 Gb showed that the container averaged at around 2.4 Gb of memory, maybe some recommended values for CPU and memory provisioning could be present in the documentation.

Regarding my second issue of only parsing old entries, I found this weird because we had this flag on in prometheus.
`--storage.tsdb.retention=1d` 

Upon further inspection I found a second WAL folder in the prometheus container created by Thanos, so Stackdriver was parsing the wrong blocks.

Pointing Stackdriver at the correct folder resulted in uploaded metrics.

**Comment by jkohen** [comment]
Thank you for chasing down the issue and providing an update. If you want to suggest a change to the documentation based on your findings, that'd be nice. I think the memory usage will depend on the scale of the deployment, so it may be hard to have a generic recommendation. Was the pod crashing with a useful message we could add to our troubleshooting docs?

**Comment by polycaster** [comment]
There was no exit message, it simply quit and stopped outputting any logs, so it can be quite sneaky
