### ISSUE TITLE
Instrument with OpenCensus

### ISSUE THREAD

**Issue by jkohen** [Stackdriver/stackdriver-prometheus-sidecar#8]
This is for monitoring the sidecar itself, not how we write the Prometheus data.

This is important so we don't rely on Prometheus to monitor the Prometheus sidecar (although that will be an option with OpenCensus).

https://opencensus.io/go/index.html

**Comment by wdhnl** [comment]
OpenCensus now supports a view type of LastValue which is like a gauge https://godoc.org/go.opencensus.io/stats/view#LastValue

**Comment by jkohen** [comment]
Thanks, Bill. We are working with OpenCensus to have a first-class gauge in Go soon, like it was added to Java https://github.com/census-instrumentation/opencensus-java/blob/master/api/src/main/java/io/opencensus/metrics/LongGauge.java

**Comment by jkohen** [comment]
This is a cleanup. We'll take care of this if necessary, but currently it's not a blocker, so I'm closing the issue.
