### ISSUE TITLE
Sidecar API retries

### ISSUE THREAD

**Issue by polycaster** [Stackdriver/stackdriver-prometheus-sidecar#85]
Hi friends,

I've tested the sidecar successfully for 24 hours.
There's a couple of takeaways from this experience.

The implementation I was attempting was at a fairly large scale, there are 4 instances of prometheus per cluster with 6 clusters in total. This gives us a total of 24 sidecars active.

In 24 hours, these sidecars were responsible for a whopping amount of *82,099,610* API calls.
This is an absolutely unacceptable amount. 
Assuming that we would average the number of metrics between instances, this translates into *3420817* per sidecar per day.

The aggregated cost of these calls (and only the API calls) was 820.99 £.

One could argue that reducing the amount of unused income metrics would be an efficient way to reduce cost (and would be right), however some of the retrying done by the sidecar is absolutely unreasonable.

Example 1:
Metric name checks are made by sending calls to the API and then checking the error response.
The regex for the name is available in the google docs, so, there is absolutely no reason why the checks can't be done locally and save everyone using your software some cash.

Example 2:
Tremendously aggressive retrying. Surely if we weren't able to upload a metric the result is not likely to change suddenly, my suggestion here would be to add exponential timeouts. 1 sec before 1st retry, 2 sec before 2nd, 4 sec before 3rd, 8 sec before 4th, etc.. (up to a certain point where it would cap)

Example 3:
There is a restriction of 1 time series per minute for a specific metric imposed by GCP, which means that if varied exporters scrape the endpoints at the rate of 3 times per minute and report on 25 metrics (20 seconds between scrapes is not that uncommon), stackdriver will make 25 valid API calls and 50 invalid ones. If you extrapolate the magnitude of metrics, this becomes absolutely unbearable and a waste of resources.

As an example of what i'm talking about here, here's the API statistics for the 24 hours:

API: Stackdriver Monitoring API 
Number of requests: *82,099,610*
% of Error API CALLS: *89*

This means that out of the 82 million calls in 1 day, 9 million were actually successful.

I intend to help fix some of these problems when I get a chance to contribute to your project, just thought i'd raise these so that you are aware or at least that you put a warning in the documentation of this project so that people can do their research on pricing and the metrics they have before deploying it.

Thank your for your time and effort.
Miguel

**Comment by jkohen** [comment]
Hi Miguel, thanks for the report, and I'm sorry to hear our Prometheus support isn't working well for you. Can you share the error messages that you are seeing, so we can understand the source of the retries?

And just to check, you mentioned multiple sidecars per cluster. Is it possible that these sidecars are trying to write to the same time series? This would happen if, for instance, you have multiple Prometheus instances scraping the same targets. This is covered in our [troubleshooting guide](https://cloud.google.com/monitoring/kubernetes-engine/prometheus#prometheus_integration_issues), have you looked at it?

**Comment by richardmarshall** [comment]
We're having a similar issue with the sidecars handling of errors. With a single sidecar container we are seeing more than 3 million API errors in a 24 hour period.

The sidecar container log is flooded with messages like these:
```
level=warn ts=2019-02-08T01:19:02.867205659Z caller=queue_manager.go:546 component=queue_manager msg="Unrecoverable error sending samples to remote storage" err="rpc error: code = InvalidArgument desc = Field timeSeries[0].points[0].distributionValue had an invalid value: Distribution |explicit_buckets.bounds| does not have at least one entry.
```

```
level=warn ts=2019-02-12T18:18:25.928533792Z caller=queue_manager.go:546 component=queue_manager msg="Unrecoverable error sending samples to remote storage" err="rpc error: code = InvalidArgument desc = Field timeSeries[0].points[0].distributionValue had an invalid value: Distribution value has a negative |count| of -9223372036854775808.
```

If we leave the container running eventually we end up hitting the stackdriver monitoring API rate limit.
```
level=warn ts=2019-02-07T17:08:09.398195427Z caller=queue_manager.go:546 component=queue_manager msg="Unrecoverable error sending samples to remote storage" err="rpc error: code = ResourceExhausted desc = Quota exceeded for quota metric 'monitoring.googleapis.com/default_requests' and limit 'DefaultRequestsPerMinutePerUser' of service 'monitoring.googleapis.com' for consumer 'project_number:***********'."```

**Comment by jkohen** [comment]
@richardmarshall thank you for the additional information. The problem as I understand it is that we generate a histogram metric with no buckets.

I'll change the code so that if it detects a histogram that is causing this problem, it will prevent the error and print a warning. The reason for the warning is to ensure that we are not masking a more serious bug. If through that warning we learn that there is no serious bug, I will later remove the warning and consider this closed.

For future reference and in case you are savvy with Prometheus, we are probably seeing a Prometheus metric of type Distribution that has the *_sum or *_count time series, but not a corresponding *_bucket time series. This is the relevant [code that does the transformation](https://github.com/Stackdriver/stackdriver-prometheus-sidecar/blob/bfe393828ef37496968bada6060b35c5d3dfec25/retrieval/transform.go#L183).

*As for the API quota*, you have to request a bump through the Cloud Console.

**Comment by polycaster** [comment]
Do you have any benchmarks for amount of API calls @jkohen unfortunately I don't have the logs anymore. But the majority of errors were due to the limitation of 1 timeseries / minute.

About our prometheus instances, they are scraping different exporters, however we do have a kafka exporter which produces a high volume of time series and therefore more data points for the sidecar to fail to write.

But it seems that in @richardmarshall's case, 1 container with a small range of errors still generates a fairly high amount of API calls.
Is it expected behaviour to see this scale if you have even just one kind of error in your logs?

How does this benchmark on a desired state, are the number of API calls substantially lower?

**Comment by jkohen** [comment]
Are you by any chance using recording rules? There is an assumption in the translation of histograms from Prometheus to Stackdriver that we just learned isn't true for recording rules. If that's your case, a workaround would be to temporarily avoid sending histogram from recording rules to Stackdriver and send the raw data instead.

[The assumption in `buildDistribution`](https://github.com/Stackdriver/stackdriver-prometheus-sidecar/blob/bfe393828ef37496968bada6060b35c5d3dfec25/retrieval/transform.go#L197-L198)

**Comment by polycaster** [comment]
That's on the money. We have 10 recording rules * 5 (each cluster)

**Comment by jkohen** [comment]
Thanks for your help, and I'm glad we could help. I'm going to close this issue since we haven't heard back from you. Please let us know if retries are still an issue after the issue with the recording rules was addressed.
